// TODO generate this file automatically with https://github.com/awslabs/smithy-rs

#[cfg_attr(rustfmt, rustfmt_skip)]
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum S3Ops {
    AbortMultipartUpload,
    CompleteMultipartUpload,
    CopyObject,
    CreateBucket,
    CreateMultipartUpload,
    DeleteBucket,
    DeleteBucketAnalyticsConfiguration,
    DeleteBucketCors,
    DeleteBucketEncryption,
    DeleteBucketIntelligentTieringConfiguration,
    DeleteBucketInventoryConfiguration,
    DeleteBucketLifecycle,
    DeleteBucketMetricsConfiguration,
    DeleteBucketOwnershipControls,
    DeleteBucketPolicy,
    DeleteBucketReplication,
    DeleteBucketTagging,
    DeleteBucketWebsite,
    DeleteObject,
    DeleteObjects,
    DeleteObjectTagging,
    DeletePublicAccessBlock,
    GetBucketAccelerateConfiguration,
    GetBucketAcl,
    GetBucketAnalyticsConfiguration,
    GetBucketCors,
    GetBucketEncryption,
    GetBucketIntelligentTieringConfiguration,
    GetBucketInventoryConfiguration,
    GetBucketLifecycleConfiguration,
    GetBucketLocation,
    GetBucketLogging,
    GetBucketMetricsConfiguration,
    GetBucketNotificationConfiguration,
    GetBucketOwnershipControls,
    GetBucketPolicy,
    GetBucketPolicyStatus,
    GetBucketReplication,
    GetBucketRequestPayment,
    GetBucketTagging,
    GetBucketVersioning,
    GetBucketWebsite,
    GetObject,
    GetObjectAcl,
    GetObjectLegalHold,
    GetObjectLockConfiguration,
    GetObjectRetention,
    GetObjectTagging,
    GetObjectTorrent,
    GetPublicAccessBlock,
    HeadBucket,
    HeadObject,
    ListBucketAnalyticsConfigurations,
    ListBucketIntelligentTieringConfigurations,
    ListBucketInventoryConfigurations,
    ListBucketMetricsConfigurations,
    ListBuckets,
    ListMultipartUploads,
    ListObjects,
    ListObjectsV2,
    ListObjectVersions,
    ListParts,
    PutBucketAccelerateConfiguration,
    PutBucketAcl,
    PutBucketAnalyticsConfiguration,
    PutBucketCors,
    PutBucketEncryption,
    PutBucketIntelligentTieringConfiguration,
    PutBucketInventoryConfiguration,
    PutBucketLifecycleConfiguration,
    PutBucketLogging,
    PutBucketMetricsConfiguration,
    PutBucketNotificationConfiguration,
    PutBucketOwnershipControls,
    PutBucketPolicy,
    PutBucketReplication,
    PutBucketRequestPayment,
    PutBucketTagging,
    PutBucketVersioning,
    PutBucketWebsite,
    PutObject,
    PutObjectAcl,
    PutObjectLegalHold,
    PutObjectLockConfiguration,
    PutObjectRetention,
    PutObjectTagging,
    PutPublicAccessBlock,
    RestoreObject,
    SelectObjectContent,
    UploadPart,
    UploadPartCopy,
    WriteGetObjectResponse,
}

#[cfg_attr(rustfmt, rustfmt_skip)]
impl From<&str> for S3Ops {
    fn from(s: &str) -> Self {
        match s {
            "AbortMultipartUpload" => Self::AbortMultipartUpload,
            "CompleteMultipartUpload" => Self::CompleteMultipartUpload,
            "CopyObject" => Self::CopyObject,
            "CreateBucket" => Self::CreateBucket,
            "CreateMultipartUpload" => Self::CreateMultipartUpload,
            "DeleteBucket" => Self::DeleteBucket,
            "DeleteBucketAnalyticsConfiguration" => Self::DeleteBucketAnalyticsConfiguration,
            "DeleteBucketCors" => Self::DeleteBucketCors,
            "DeleteBucketEncryption" => Self::DeleteBucketEncryption,
            "DeleteBucketIntelligentTieringConfiguration" => Self::DeleteBucketIntelligentTieringConfiguration,
            "DeleteBucketInventoryConfiguration" => Self::DeleteBucketInventoryConfiguration,
            "DeleteBucketLifecycle" => Self::DeleteBucketLifecycle,
            "DeleteBucketMetricsConfiguration" => Self::DeleteBucketMetricsConfiguration,
            "DeleteBucketOwnershipControls" => Self::DeleteBucketOwnershipControls,
            "DeleteBucketPolicy" => Self::DeleteBucketPolicy,
            "DeleteBucketReplication" => Self::DeleteBucketReplication,
            "DeleteBucketTagging" => Self::DeleteBucketTagging,
            "DeleteBucketWebsite" => Self::DeleteBucketWebsite,
            "DeleteObject" => Self::DeleteObject,
            "DeleteObjects" => Self::DeleteObjects,
            "DeleteObjectTagging" => Self::DeleteObjectTagging,
            "DeletePublicAccessBlock" => Self::DeletePublicAccessBlock,
            "GetBucketAccelerateConfiguration" => Self::GetBucketAccelerateConfiguration,
            "GetBucketAcl" => Self::GetBucketAcl,
            "GetBucketAnalyticsConfiguration" => Self::GetBucketAnalyticsConfiguration,
            "GetBucketCors" => Self::GetBucketCors,
            "GetBucketEncryption" => Self::GetBucketEncryption,
            "GetBucketIntelligentTieringConfiguration" => Self::GetBucketIntelligentTieringConfiguration,
            "GetBucketInventoryConfiguration" => Self::GetBucketInventoryConfiguration,
            "GetBucketLifecycleConfiguration" => Self::GetBucketLifecycleConfiguration,
            "GetBucketLocation" => Self::GetBucketLocation,
            "GetBucketLogging" => Self::GetBucketLogging,
            "GetBucketMetricsConfiguration" => Self::GetBucketMetricsConfiguration,
            "GetBucketNotificationConfiguration" => Self::GetBucketNotificationConfiguration,
            "GetBucketOwnershipControls" => Self::GetBucketOwnershipControls,
            "GetBucketPolicy" => Self::GetBucketPolicy,
            "GetBucketPolicyStatus" => Self::GetBucketPolicyStatus,
            "GetBucketReplication" => Self::GetBucketReplication,
            "GetBucketRequestPayment" => Self::GetBucketRequestPayment,
            "GetBucketTagging" => Self::GetBucketTagging,
            "GetBucketVersioning" => Self::GetBucketVersioning,
            "GetBucketWebsite" => Self::GetBucketWebsite,
            "GetObject" => Self::GetObject,
            "GetObjectAcl" => Self::GetObjectAcl,
            "GetObjectLegalHold" => Self::GetObjectLegalHold,
            "GetObjectLockConfiguration" => Self::GetObjectLockConfiguration,
            "GetObjectRetention" => Self::GetObjectRetention,
            "GetObjectTagging" => Self::GetObjectTagging,
            "GetObjectTorrent" => Self::GetObjectTorrent,
            "GetPublicAccessBlock" => Self::GetPublicAccessBlock,
            "HeadBucket" => Self::HeadBucket,
            "HeadObject" => Self::HeadObject,
            "ListBucketAnalyticsConfigurations" => Self::ListBucketAnalyticsConfigurations,
            "ListBucketIntelligentTieringConfigurations" => Self::ListBucketIntelligentTieringConfigurations,
            "ListBucketInventoryConfigurations" => Self::ListBucketInventoryConfigurations,
            "ListBucketMetricsConfigurations" => Self::ListBucketMetricsConfigurations,
            "ListBuckets" => Self::ListBuckets,
            "ListMultipartUploads" => Self::ListMultipartUploads,
            "ListObjects" => Self::ListObjects,
            "ListObjectsV2" => Self::ListObjectsV2,
            "ListObjectVersions" => Self::ListObjectVersions,
            "ListParts" => Self::ListParts,
            "PutBucketAccelerateConfiguration" => Self::PutBucketAccelerateConfiguration,
            "PutBucketAcl" => Self::PutBucketAcl,
            "PutBucketAnalyticsConfiguration" => Self::PutBucketAnalyticsConfiguration,
            "PutBucketCors" => Self::PutBucketCors,
            "PutBucketEncryption" => Self::PutBucketEncryption,
            "PutBucketIntelligentTieringConfiguration" => Self::PutBucketIntelligentTieringConfiguration,
            "PutBucketInventoryConfiguration" => Self::PutBucketInventoryConfiguration,
            "PutBucketLifecycleConfiguration" => Self::PutBucketLifecycleConfiguration,
            "PutBucketLogging" => Self::PutBucketLogging,
            "PutBucketMetricsConfiguration" => Self::PutBucketMetricsConfiguration,
            "PutBucketNotificationConfiguration" => Self::PutBucketNotificationConfiguration,
            "PutBucketOwnershipControls" => Self::PutBucketOwnershipControls,
            "PutBucketPolicy" => Self::PutBucketPolicy,
            "PutBucketReplication" => Self::PutBucketReplication,
            "PutBucketRequestPayment" => Self::PutBucketRequestPayment,
            "PutBucketTagging" => Self::PutBucketTagging,
            "PutBucketVersioning" => Self::PutBucketVersioning,
            "PutBucketWebsite" => Self::PutBucketWebsite,
            "PutObject" => Self::PutObject,
            "PutObjectAcl" => Self::PutObjectAcl,
            "PutObjectLegalHold" => Self::PutObjectLegalHold,
            "PutObjectLockConfiguration" => Self::PutObjectLockConfiguration,
            "PutObjectRetention" => Self::PutObjectRetention,
            "PutObjectTagging" => Self::PutObjectTagging,
            "PutPublicAccessBlock" => Self::PutPublicAccessBlock,
            "RestoreObject" => Self::RestoreObject,
            "SelectObjectContent" => Self::SelectObjectContent,
            "UploadPart" => Self::UploadPart,
            "UploadPartCopy" => Self::UploadPartCopy,
            "WriteGetObjectResponse" => Self::WriteGetObjectResponse,
            _ => panic!("Unknown S3 operation name: {}", s),
        }
    }
}
