// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn serialize_structure_crate_output_abort_multipart_upload_output(
    input: &crate::output::AbortMultipartUploadOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_no_such_upload(
    input: &crate::error::NoSuchUpload,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_complete_multipart_upload_output(
    input: &crate::output::CompleteMultipartUploadOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_copy_object_output(
    input: &crate::output::CopyObjectOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_object_not_in_active_tier_error(
    input: &crate::error::ObjectNotInActiveTierError,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_create_bucket_output(
    input: &crate::output::CreateBucketOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_bucket_already_owned_by_you(
    input: &crate::error::BucketAlreadyOwnedByYou,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_bucket_already_exists(
    input: &crate::error::BucketAlreadyExists,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_create_multipart_upload_output(
    input: &crate::output::CreateMultipartUploadOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_output(
    input: &crate::output::DeleteBucketOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_analytics_configuration_output(
    input: &crate::output::DeleteBucketAnalyticsConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_cors_output(
    input: &crate::output::DeleteBucketCorsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_encryption_output(
    input: &crate::output::DeleteBucketEncryptionOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_intelligent_tiering_configuration_output(
    input: &crate::output::DeleteBucketIntelligentTieringConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_inventory_configuration_output(
    input: &crate::output::DeleteBucketInventoryConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_lifecycle_output(
    input: &crate::output::DeleteBucketLifecycleOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_metrics_configuration_output(
    input: &crate::output::DeleteBucketMetricsConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_ownership_controls_output(
    input: &crate::output::DeleteBucketOwnershipControlsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_policy_output(
    input: &crate::output::DeleteBucketPolicyOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_replication_output(
    input: &crate::output::DeleteBucketReplicationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_tagging_output(
    input: &crate::output::DeleteBucketTaggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_bucket_website_output(
    input: &crate::output::DeleteBucketWebsiteOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_object_output(
    input: &crate::output::DeleteObjectOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_objects_output(
    input: &crate::output::DeleteObjectsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_object_tagging_output(
    input: &crate::output::DeleteObjectTaggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_delete_public_access_block_output(
    input: &crate::output::DeletePublicAccessBlockOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_accelerate_configuration_output(
    input: &crate::output::GetBucketAccelerateConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_acl_output(
    input: &crate::output::GetBucketAclOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_analytics_configuration_output(
    input: &crate::output::GetBucketAnalyticsConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_cors_output(
    input: &crate::output::GetBucketCorsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_encryption_output(
    input: &crate::output::GetBucketEncryptionOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_intelligent_tiering_configuration_output(
    input: &crate::output::GetBucketIntelligentTieringConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_inventory_configuration_output(
    input: &crate::output::GetBucketInventoryConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_lifecycle_configuration_output(
    input: &crate::output::GetBucketLifecycleConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_location_output(
    input: &crate::output::GetBucketLocationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_logging_output(
    input: &crate::output::GetBucketLoggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_metrics_configuration_output(
    input: &crate::output::GetBucketMetricsConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_notification_configuration_output(
    input: &crate::output::GetBucketNotificationConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_ownership_controls_output(
    input: &crate::output::GetBucketOwnershipControlsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_policy_output(
    input: &crate::output::GetBucketPolicyOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_policy_status_output(
    input: &crate::output::GetBucketPolicyStatusOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_replication_output(
    input: &crate::output::GetBucketReplicationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_request_payment_output(
    input: &crate::output::GetBucketRequestPaymentOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_tagging_output(
    input: &crate::output::GetBucketTaggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_versioning_output(
    input: &crate::output::GetBucketVersioningOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_bucket_website_output(
    input: &crate::output::GetBucketWebsiteOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_no_such_key(
    input: &crate::error::NoSuchKey,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_invalid_object_state(
    input: &crate::error::InvalidObjectState,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    if let Some(var_1) = &input.access_tier {
        let mut inner_writer = scope.start_el("AccessTier").finish();
        inner_writer.data(var_1.as_str());
    }
    if let Some(var_2) = &input.storage_class {
        let mut inner_writer = scope.start_el("StorageClass").finish();
        inner_writer.data(var_2.as_str());
    }
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_object_acl_output(
    input: &crate::output::GetObjectAclOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_object_legal_hold_output(
    input: &crate::output::GetObjectLegalHoldOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_object_lock_configuration_output(
    input: &crate::output::GetObjectLockConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_object_retention_output(
    input: &crate::output::GetObjectRetentionOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_object_tagging_output(
    input: &crate::output::GetObjectTaggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_get_public_access_block_output(
    input: &crate::output::GetPublicAccessBlockOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_head_bucket_output(
    input: &crate::output::HeadBucketOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_not_found(
    input: &crate::error::NotFound,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_head_object_output(
    input: &crate::output::HeadObjectOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_bucket_analytics_configurations_output(
    input: &crate::output::ListBucketAnalyticsConfigurationsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_bucket_intelligent_tiering_configurations_output(
    input: &crate::output::ListBucketIntelligentTieringConfigurationsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_bucket_inventory_configurations_output(
    input: &crate::output::ListBucketInventoryConfigurationsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_bucket_metrics_configurations_output(
    input: &crate::output::ListBucketMetricsConfigurationsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_buckets_output(
    input: &crate::output::ListBucketsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_multipart_uploads_output(
    input: &crate::output::ListMultipartUploadsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_objects_output(
    input: &crate::output::ListObjectsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_no_such_bucket(
    input: &crate::error::NoSuchBucket,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_objects_v2_output(
    input: &crate::output::ListObjectsV2Output,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_object_versions_output(
    input: &crate::output::ListObjectVersionsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_list_parts_output(
    input: &crate::output::ListPartsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_accelerate_configuration_output(
    input: &crate::output::PutBucketAccelerateConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_acl_output(
    input: &crate::output::PutBucketAclOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_analytics_configuration_output(
    input: &crate::output::PutBucketAnalyticsConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_cors_output(
    input: &crate::output::PutBucketCorsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_encryption_output(
    input: &crate::output::PutBucketEncryptionOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_intelligent_tiering_configuration_output(
    input: &crate::output::PutBucketIntelligentTieringConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_inventory_configuration_output(
    input: &crate::output::PutBucketInventoryConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_lifecycle_configuration_output(
    input: &crate::output::PutBucketLifecycleConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_logging_output(
    input: &crate::output::PutBucketLoggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_metrics_configuration_output(
    input: &crate::output::PutBucketMetricsConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_notification_configuration_output(
    input: &crate::output::PutBucketNotificationConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_ownership_controls_output(
    input: &crate::output::PutBucketOwnershipControlsOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_policy_output(
    input: &crate::output::PutBucketPolicyOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_replication_output(
    input: &crate::output::PutBucketReplicationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_request_payment_output(
    input: &crate::output::PutBucketRequestPaymentOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_tagging_output(
    input: &crate::output::PutBucketTaggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_versioning_output(
    input: &crate::output::PutBucketVersioningOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_bucket_website_output(
    input: &crate::output::PutBucketWebsiteOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_object_output(
    input: &crate::output::PutObjectOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_object_acl_output(
    input: &crate::output::PutObjectAclOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_object_legal_hold_output(
    input: &crate::output::PutObjectLegalHoldOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_object_lock_configuration_output(
    input: &crate::output::PutObjectLockConfigurationOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_object_retention_output(
    input: &crate::output::PutObjectRetentionOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_object_tagging_output(
    input: &crate::output::PutObjectTaggingOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_put_public_access_block_output(
    input: &crate::output::PutPublicAccessBlockOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_restore_object_output(
    input: &crate::output::RestoreObjectOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_error_object_already_in_active_tier_error(
    input: &crate::error::ObjectAlreadyInActiveTierError,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_upload_part_output(
    input: &crate::output::UploadPartOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_upload_part_copy_output(
    input: &crate::output::UploadPartCopyOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

pub fn serialize_structure_crate_output_write_get_object_response_output(
    input: &crate::output::WriteGetObjectResponseOutput,
    writer: aws_smithy_xml::encode::ElWriter,
) -> Result<(), aws_smithy_http::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}
