//! This file is generated by build.rs. DO NOT EDIT.
#![allow(unused)]

use crate::{http::*, xml::*};
use aws_smithy_http::byte_stream::ByteStream;
use aws_smithy_xml::decode::{Document, ScopedDecoder};
use hyper::{body::Bytes, header::HeaderValue, Body, StatusCode};

include!(concat!(env!("OUT_DIR"), "/s3.1.rs"));
include!(concat!(env!("OUT_DIR"), "/s3.2.rs"));
include!(concat!(env!("OUT_DIR"), "/s3.3.rs"));
include!(concat!(env!("OUT_DIR"), "/s3.4.rs"));
