name: RELEASE

on: release

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Fuse
        run: sudo apt-get install -y fuse libfuse-dev pkg-config
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Rust
        uses: Swatinem/rust-cache@v1
      - name: Make Build Release
        run: make build RELEASE=1


      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/release/s3
          asset_name: s3-linux
          prerelease: true
          overwrite: true
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            target/release/s3
            target/release/s3d
